<div class="container">
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <div class="login-panel panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Please Sign In</h3>
                </div>
                <div class="panel-body">
                    <?php $errors = $this->flashMessenger()->render('error') ?>
                    <?php if(!empty($errors)): ?>
                        <div class="alert alert-danger alert-dismissable">
                            <?php echo $errors ?>
                        </div>
                    <?php endif; ?>

                    <form role="form" method="post" action="<?php echo $this->url('authenticate') ?>">
                        <fieldset>
                            <div class="form-group">
                                <input class="form-control" placeholder="Username" name="username" type="username" autofocus>
                            </div>
                            <div class="form-group">
                                <input class="form-control" placeholder="Password" name="password" type="password" value="">
                            </div>
                            <!-- Change this to a button or input when using this as a form -->
                            <a href="index.html" class="btn btn-lg btn-success btn-block btn-submit">Login</a>
                        </fieldset>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<?php $this->inlineScript()->captureStart();
echo <<<JS
    $('form .btn.btn-submit').click(function(e) {
        e.preventDefault();

        $(this).parents('form').trigger('submit');

        return false;
    });
JS;
$this->inlineScript()->captureEnd(); ?>